# Importing the Dependencies

In [220]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Data Collection & Processing

In [223]:
credit_card_data = pd.read_csv('creditcard.csv')

# To get the first 5 Rows of Data

In [225]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

# Dataset Information

In [227]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

# Checking the Number of Missing Values in Dataset

In [229]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

# Distribution of Legit Transactions & Fraudulent Transactions

In [231]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

**This Data is highly unbalanced**

**0 --> Normal Transactions**

**1 --> Fradulent Transactions**

# Separating the Data for Analysis

In [241]:
legit = credit_card_data[credit_card_data.Class == 0]
Fraud = credit_card_data[credit_card_data.Class == 1]

In [242]:
legit.shape

(284315, 31)

In [243]:
Fraud.shape

(492, 31)

# Statistical Measure about data

In [248]:
legit['Amount'].describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [250]:
Fraud['Amount'].describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

# Compare the values for both Transactions

In [253]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# Under-Samling

* Building a sample dataset containing similar distribution of Normal and Fradulent transactions

* No. of Fradulent transactions = 492

In [258]:
legit_sample = legit.sample(n = 492)

# Concatenating 2 Dataframes

In [261]:
new_dataset = pd.concat([legit_sample,Fraud], axis = 0)

In [263]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
253572,156318.0,1.760679,-0.633088,-1.656913,0.991470,-0.268993,-0.427674,-0.334734,-0.111740,-0.391613,...,-0.348485,-0.748839,0.102771,0.413736,-0.189019,-0.717567,0.058639,0.052965,174.00,0
198362,132458.0,1.957960,-0.677669,-0.395253,0.762448,-0.685747,0.201289,-0.854448,0.198542,1.820618,...,0.199416,0.907851,0.061666,0.730593,0.001207,0.568559,-0.009303,-0.047854,14.39,0
130333,79333.0,1.400751,-1.365262,1.334405,-1.171384,-2.226926,-0.168042,-1.711199,0.194649,-1.210946,...,-0.186484,-0.025771,0.089856,0.519056,0.170698,-0.223218,0.072015,0.022653,10.00,0
94383,64862.0,1.230328,-0.142772,0.577320,0.823059,-0.097718,1.110052,-0.711637,0.359216,0.778019,...,-0.126083,-0.194498,-0.228647,-1.393646,0.609102,-0.318976,0.065074,0.010349,9.99,0
12066,20926.0,1.203622,0.882222,0.261395,2.691929,0.344822,-0.766535,0.553966,-0.417283,0.093518,...,-0.146143,-0.184837,-0.116364,0.361097,0.731489,0.024955,-0.063575,0.008311,18.31,0

In [265]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [267]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96780.215447,-0.024694,0.044763,-0.078211,0.050462,0.015418,0.062002,-0.078108,-0.245575,0.036013,...,0.014985,0.030048,-0.034405,0.045150,0.004664,-0.029970,-0.068800,-0.024853,0.009375,92.065935
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

# Splitting the Data into Features and Target

In [270]:
X = new_dataset.drop('Class', axis = 1)
Y = new_dataset['Class']

# Splitting the data into Training and Testing Data

In [273]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify = Y, random_state = 2)

In [275]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

# Model Training

In [278]:
model = LogisticRegression()

# Training the Logictic regression Model with Training Data

In [281]:
model.fit(X_train, Y_train)

C:\Users\offic\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Model Evaluation on Accuracy Score

* Accuracy on training data

In [285]:
X_train_prediction = model.predict(X_train)

In [287]:
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [289]:
print("Accuracy Score on training Data :",training_data_accuracy)

Accuracy Score on training Data : 0.9377382465057179

* Accuracy on test data

In [292]:
X_test_prediction = model.predict(X_test)

In [294]:
testing_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [296]:
print("Accuracy Score on testing Data :",testing_data_accuracy)

Accuracy Score on testing Data : 0.9137055837563451